<a href="https://colab.research.google.com/github/Bhargavimarathe/INTERNSHIP-2026/blob/main/assignments/week4/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
Write a function safe_divide(a, b) that divides two numbers and handles ZeroDivisionError
and TypeError separately, printing an appropriate message for each. Use a finally block to print 'Operation attempted.'
 regardless of the outcome. Test it with valid numbers, division by zero, and a string input.
""";

In [ ]:
def safe_divide(a, b):
    try:
        result = a / b
        print("Result:", result)

    except ZeroDivisionError:
        print("Error: Cannot divide by zero.")

    except TypeError:
        print("Error: Invalid data type. Please enter numbers only.")

    finally:
        print("Operation attempted.")


print("Test 1: Valid numbers")
safe_divide(10, 2)

print("\nTest 2: Division by zero")
safe_divide(10, 0)

print("\nTest 3: String input")
safe_divide(10, "5")

Test 1: Valid numbers
Result: 5.0
Operation attempted.

Test 2: Division by zero
Error: Cannot divide by zero.
Operation attempted.

Test 3: String input
Error: Invalid data type. Please enter numbers only.
Operation attempted.


In [ ]:
"""
2.

Write a function validate_age(age) that raises a custom exception InvalidAgeError
 (a class you define, inheriting from Exception) if age is negative or greater than 120.
  Catch this exception in a calling block and print a user-friendly message. Test it with at least 3 different values.
  """;

In [ ]:
class InvalidAgeError(Exception):
    pass

class InvalidAgeError(Exception):
    pass

def validate_age(age):
    if age < 0 or age > 120:
        raise InvalidAgeError("Invalid age entered.")
    elif age < 18:
        print("Not eligible to vote.")
    else:
        print("Eligible to vote.")

for i in range(3):
    try:
        age = int(input("Enter age: "))
        validate_age(age)
    except InvalidAgeError as e:
        print("Error:", e)

Enter age: 18
Eligible to vote.
Enter age: 16
Not eligible to vote.
Enter age: 121
Error: Invalid age entered.


In [ ]:
"""
3

Write a program that repeatedly asks the user (use a loop with at least 3 simulated inputs in a list, e.g. user_inputs = ['10', 'abc', '0', '5']) to enter a number and divide 100 by it. Handle the following in a single try block using multiple except clauses:

a) ValueError if the input is not a number.

b) ZeroDivisionError if the input is zero.

c) A generic Exception as a catch-all for anything else.

Print the result if successful, otherwise print which error occurred.
""";

In [ ]:
user_inputs = ['10', 'abc', '0', '5']

for value in user_inputs:
    try:
        num = int(value)
        print("Result:", 100 / num)

    except ValueError:
        print("Error: Input is not a number.")

    except ZeroDivisionError:
        print("Error: Cannot divide by zero.")

    except Exception:
        print("Error: Something went wrong.")

Result: 10.0
Error: Input is not a number.
Error: Cannot divide by zero.
Result: 20.0


In [ ]:
"""
Section B — NumPy
4.

Create a 1D NumPy array of integers from 1 to 20. Perform the following:

a) Reshape it into a 4x5 2D array.

b) Print the sum of each row and each column.

c) Extract all elements greater than 10 using boolean indexing.

d) Replace all even numbers in the array with -1.
""";



In [ ]:
import numpy as np

arr = np.arange(1, 21)

arr2 = arr.reshape(4, 5)
print("4x5 Array:\n", arr2)

print("Row Sum:", arr2.sum(axis=1))
print("Column Sum:", arr2.sum(axis=0))

print("Elements greater than 10:", arr[arr > 10])

arr[arr % 2 == 0] = -1
print("Array after replacing even numbers:", arr)

4x5 Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Row Sum: [15 40 65 90]
Column Sum: [34 38 42 46 50]
Elements greater than 10: [11 12 13 14 15 16 17 18 19 20]
Array after replacing even numbers: [ 1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19 -1]


In [ ]:
"""
Create two NumPy arrays A and B as shown below and perform:

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

a) Element-wise addition, subtraction, and multiplication.

b) Matrix multiplication using np.dot() or the @ operator.

c) Transpose of A.

d) The determinant and inverse of A using np.linalg.
""";

In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Addition:\n", A + B)

print("Subtraction:\n", A - B)

print("Multiplication:\n", A * B)

print("Matrix Multiplication:\n", np.dot(A, B))

print("Transpose of A:\n", A.T)

print("Determinant of A:", np.linalg.det(A))

print("Inverse of A:\n", np.linalg.inv(A))

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
Determinant of A: -2.0000000000000004
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
"""
Generate a NumPy array of 15 random integers between 1 and 100 using np.random.randint() (set a seed of 42 for reproducibility). Then:

a) Find the mean, median, standard deviation, min, and max.

b) Sort the array in descending order.

c) Find the indices of the 3 largest values using np.argsort().

d) Normalize the array so all values lie between 0 and 1.
""";

In [ ]:
import numpy as np

np.random.seed(42)

arr = np.random.randint(1, 101, 15)

print("Array:", arr)

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))

print("Descending Order:", np.sort(arr)[::-1])

print("Indices of 3 Largest Values:", np.argsort(arr)[-3:])

normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print("Normalized Array:", normalized)

Array: [ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22]
Mean: 58.06666666666667
Median: 72.0
Standard Deviation: 31.4843170836247
Minimum: 3
Maximum: 100
Descending Order: [100  93  88  87  83  75  75  72  61  52  24  22  21  15   3]
Indices of 3 Largest Values: [10  1 11]
Normalized Array: [0.50515464 0.92783505 0.12371134 0.71134021 0.59793814 0.18556701
 0.82474227 0.86597938 0.74226804 0.74226804 0.87628866 1.
 0.21649485 0.         0.19587629]


In [ ]:
"""
7.

Create a Pandas DataFrame from the dictionary below and perform the following:

data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}

a) Display the first 3 rows and the data types of each column.

b) Add a new column Grade based on Score (>=90 'A', >=75 'B', else 'C').

c) Sort the DataFrame by Score in descending order.

d) Filter rows where Department is 'AI'.
""";

In [ ]:
import pandas as pd

data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}

df = pd.DataFrame(data)

print("First 3 Rows:")
print(df.head(3))

print("\nData Types:")
print(df.dtypes)

df["Grade"] = df["Score"].apply(
    lambda x: "A" if x >= 90 else "B" if x >= 75 else "C"
)

print("\nDataFrame with Grade:")
print(df)

print("\nSorted by Score (Descending):")
print(df.sort_values(by="Score", ascending=False))

print("\nStudents from AI Department:")
print(df[df["Department"] == "AI"])

First 3 Rows:
    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79

Data Types:
Name          object
Age            int64
Department    object
Score          int64
dtype: object

DataFrame with Grade:
    Name  Age    Department  Score Grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C

Sorted by Score (Descending):
    Name  Age    Department  Score Grade
3  Meera   22       Web Dev     95     A
1  Priya   21  Data Science     92     A
0  Aarav   23            AI     88     B
2  Karan   25            AI     79     B
4  Sahil   24  Data Science     67     C

Students from AI Department:
    Name  Age Department  Score Grade
0  Aarav   23         AI     88     B
2  Karan   25         AI     79     B


In [ ]:
"""
8.

Using the same DataFrame from Q7:

a) Group by Department and find the average Score for each.

b) Find the row with the highest Score using idxmax().

c) Rename the column Score to Marks.

d) Drop the Age column and display the resulting DataFrame.
""";

In [ ]:
import pandas as pd

data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}

df = pd.DataFrame(data)

print("Average Score by Department:")
print(df.groupby("Department")["Score"].mean())

print("\nRow with Highest Score:")
print(df.loc[df["Score"].idxmax()])

df.rename(columns={"Score": "Marks"}, inplace=True)

print("\nDataFrame after Renaming Score to Marks:")
print(df)

df.drop("Age", axis=1, inplace=True)

print("\nDataFrame after Dropping Age Column:")
print(df)

Average Score by Department:
Department
AI              83.5
Data Science    79.5
Web Dev         95.0
Name: Score, dtype: float64

Row with Highest Score:
Name            Meera
Age                22
Department    Web Dev
Score              95
Name: 3, dtype: object

DataFrame after Renaming Score to Marks:
    Name  Age    Department  Marks
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
3  Meera   22       Web Dev     95
4  Sahil   24  Data Science     67

DataFrame after Dropping Age Column:
    Name    Department  Marks
0  Aarav            AI     88
1  Priya  Data Science     92
2  Karan            AI     79
3  Meera       Web Dev     95
4  Sahil  Data Science     67


In [ ]:
"""
9.

Create a DataFrame with some missing values as shown below and handle them:

import numpy as np

data = {
    "Product": ["Pen", "Notebook", "Eraser", "Sharpener", "Ruler"],
    "Price": [10, np.nan, 5, 8, np.nan],
    "Stock": [100, 50, np.nan, 30, 20]
}

a) Check the number of missing values in each column using isnull().sum().

b) Fill missing Price values with the column mean.

c) Drop rows where Stock is still missing.

d) Save the cleaned DataFrame to a CSV file named cleaned_products.csv without the index.
""";

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Product": ["Pen", "Notebook", "Eraser", "Sharpener", "Ruler"],
    "Price": [10, np.nan, 5, 8, np.nan],
    "Stock": [100, 50, np.nan, 30, 20]
}

df = pd.DataFrame(data)

print("Missing Values in Each Column:")
print(df.isnull().sum())

df["Price"].fillna(df["Price"].mean(), inplace=True)

print("\nDataFrame after Filling Missing Price Values:")
print(df)

df = df.dropna(subset=["Stock"])

print("\nDataFrame after Dropping Rows with Missing Stock:")
print(df)

df.to_csv("cleaned_products.csv", index=False)

print("\nData saved to cleaned_products.csv")

Missing Values in Each Column:
Product    0
Price      2
Stock      1
dtype: int64

DataFrame after Filling Missing Price Values:
     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
2     Eraser   5.000000    NaN
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0

DataFrame after Dropping Rows with Missing Stock:
     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0

Data saved to cleaned_products.csv


/tmp/ipykernel_482/2035328451.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Price"].fillna(df["Price"].mean(), inplace=True)


In [ ]:
"""
10.

Read the CSV file created in Q9 (cleaned_products.csv) back into a new DataFrame and:

a) Print its shape and column names.

b) Add a new column Total_Value as Price multiplied by Stock.

c) Use describe() to print summary statistics of the numeric columns.

d) Wrap the file reading step in a try-except block to handle the case where the file does not exist (FileNotFoundError).
""";

In [ ]:
import pandas as pd

try:
    df = pd.read_csv("cleaned_products.csv")

    print("Shape of DataFrame:")
    print(df.shape)

    print("\nColumn Names:")
    print(df.columns)

    df["Total_Value"] = df["Price"] * df["Stock"]

    print("\nDataFrame with Total_Value:")
    print(df)

    print("\nSummary Statistics:")
    print(df.describe())

except FileNotFoundError:
    print("Error: cleaned_products.csv file not found.")

Shape of DataFrame:
(4, 3)

Column Names:
Index(['Product', 'Price', 'Stock'], dtype='object')

DataFrame with Total_Value:
     Product      Price  Stock  Total_Value
0        Pen  10.000000  100.0  1000.000000
1   Notebook   7.666667   50.0   383.333333
2  Sharpener   8.000000   30.0   240.000000
3      Ruler   7.666667   20.0   153.333333

Summary Statistics:
           Price       Stock  Total_Value
count   4.000000    4.000000     4.000000
mean    8.333333   50.000000   444.166667
std     1.122167   35.590261   382.500303
min     7.666667   20.000000   153.333333
25%     7.666667   27.500000   218.333333
50%     7.833333   40.000000   311.666667
75%     8.500000   62.500000   537.500000
max    10.000000  100.000000  1000.000000
