<a href="https://colab.research.google.com/github/Bhargavimarathe/BhargaviMarathe/blob/main/daily_codes/week4/array_numpy_jun15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy

In [ ]:
import numpy as np

In [ ]:
# creating arrays

In [ ]:
sample_array=np.array([1,2,3,4])

In [ ]:
sample_array

array([1, 2, 3, 4])

In [ ]:
# 2D array(matrix) with 2 rows and 2 columns

In [ ]:
sample_array_2= np.array([[1,2],[3,4]])

In [ ]:
sample_array_2

array([[1, 2],
       [3, 4]])

In [ ]:
sample_array_2= np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
sample_array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# 3D tensor(2 matrices,each with 2 rows and 2 columns)

In [ ]:
sample_tensor_3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [ ]:
sample_tensor_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# Dimension

In [ ]:
# 0D array= (Scalar)5
# 1D array = (vector) [1,2,3,4]
# 2D array = (matrix) {rows,columns}
# 3D array = (tensor) (page, rows,columns)

In [ ]:
# array properties

In [ ]:
sample_array=np.array([[1,2,3],[4,5,6]])

In [ ]:
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# shape

In [ ]:
sample_array.shape

(2, 3)

In [ ]:
sample_array.ndim

2

In [ ]:
#total_elements

In [ ]:
sample_array.size

6

In [ ]:
# data type

In [ ]:
sample_array.dtype

dtype('int64')

In [ ]:
# 3d array

In [ ]:
sample_tensor= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [ ]:
sample_tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# shape

In [ ]:
sample_tensor.shape

(2, 2, 2)

In [ ]:
sample_tensor.ndim

3

In [ ]:
sample_tensor.size

8

In [ ]:
sample_tensor.dtype

dtype('int64')

In [ ]:
# special arrays

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# indexing and slicing

In [ ]:
sample_array=np.array([10,20,30,40])

In [ ]:
sample_array

array([10, 20, 30, 40])

In [ ]:
sample_array[0]

np.int64(10)

In [ ]:
sample_array[2]

np.int64(30)

In [ ]:
sample_array[-1]

np.int64(40)

In [ ]:
# slicing

In [ ]:
sample_array[1:3]

array([20, 30])

In [ ]:
# array operations

In [ ]:
a=np.array([1,2,3])

In [ ]:
b=np.array([4,5,6])

In [ ]:
a

array([1, 2, 3])

In [ ]:
b

array([4, 5, 6])

In [ ]:
a+b

array([5, 7, 9])

In [ ]:
a-b

array([-3, -3, -3])

In [ ]:
a*b

array([ 4, 10, 18])

In [ ]:
a/b

array([0.25, 0.4 , 0.5 ])

In [ ]:
a%b

array([1, 2, 3])

In [ ]:
a//b

array([0, 0, 0])

In [ ]:
a=np.array([11,22,33])

In [ ]:
b=np.array([22,44,66])

In [ ]:
a+b

array([33, 66, 99])

In [ ]:
a-b

array([-11, -22, -33])

In [ ]:
a*b

array([ 242,  968, 2178])

In [ ]:
a/b

array([0.5, 0.5, 0.5])

In [ ]:
a%b

array([11, 22, 33])

In [ ]:
a//b

array([0, 0, 0])

In [ ]:
# mathematical functions

In [ ]:
sample_array=np.array([1,4,9])

In [ ]:
sample_array

array([1, 4, 9])

In [ ]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [ ]:
sample_array=np.array([27,196,125])

In [ ]:
sample_array

array([ 27, 196, 125])

In [ ]:
np.sqrt(sample_array)

array([ 5.19615242, 14.        , 11.18033989])

In [ ]:
np.exp(sample_array)

array([5.32048241e+11, 1.32348326e+85, 1.93557604e+54])

In [ ]:
sample_array=np.array([26,42,88])

In [ ]:
np.exp(sample_array)

array([1.95729609e+11, 1.73927494e+18, 1.65163625e+38])

In [ ]:
np.log(sample_array)

array([3.25809654, 3.73766962, 4.47733681])

In [ ]:
# statistical funcytions

In [ ]:
sample_array=np.array([1,2,3,4,5])

In [ ]:
sample_array

array([1, 2, 3, 4, 5])

In [ ]:
np.mean(sample_array)

np.float64(3.0)

In [ ]:
np.median(sample_array)

np.float64(3.0)

In [ ]:
np.std(sample_array)

np.float64(1.4142135623730951)

In [ ]:
np.min(sample_array)

np.int64(1)

In [ ]:
np.max(sample_array)

np.int64(5)

In [ ]:
# reshaping array

In [ ]:
sample_array = np.arange(0, 6)

In [ ]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [ ]:
 reshaped= sample_array.reshape(2,3)

In [ ]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# flattening

In [ ]:
sample_array=np.array([[1,2,],[3,4]])

In [ ]:
sample_array

array([[1, 2],
       [3, 4]])

In [ ]:
sample_array.flatten()

array([1, 2, 3, 4])

In [ ]:
sample_tnsor_3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])e

In [ ]:
sample_tensor_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
sample_tensor_3.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# joining arrays

In [ ]:
a=np.array([1,2,3])

In [ ]:
b=np.array([4,5,6])

In [ ]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
# spliting arrays

In [ ]:
sample_array=np.array([1,2,3,4,5,6])

In [ ]:
sample_array

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.split(sample_array, 2)

[array([1, 2, 3]), array([4, 5, 6])]

In [ ]:
# random module

In [ ]:
np.random.rand(3)

array([0.16978189, 0.12916537, 0.26508342])

In [ ]:
np.random.randint(1,10,5)

array([3, 1, 6, 8, 9])

In [ ]:
# Axis concept

In [ ]:
sample_array=np.array([[1,2],[3,4]])

In [ ]:
sample_array

array([[1, 2],
       [3, 4]])

In [ ]:
np.sum(sample_array, axis=0) # columns wise sum

array([4, 6])

In [ ]:
np.sum(sample_array, axis=1)  # row wise sum

array([3, 7])

In [ ]:
# NaN and missing values

In [ ]:
sample_array=np.array([1,np.nan,3,4])

In [ ]:
sample_array

array([ 1., nan,  3.,  4.])

In [ ]:
np.isnan(sample_array)

array([False,  True, False, False])

In [ ]:
"""
create 2 numpy arrays and perform element wise addition substraction ,
multipliation and modulas operations
""";

In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Modulus:", a % b)

Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Modulus: [0 0 0 0]


In [ ]:
import numpy as np

In [ ]:
a=np.arange(1000000)
l= list(a)

In [ ]:
import time
time.time()

1781588456.0769298

In [ ]:
# time taken by list
start_time = time.time()
new1 = [i * 2 for i in l]
time_taken_l = time.time() - start_time

print(f"Time taken by list is {time_taken_l}")

Time taken by list is 0.05875563621520996


In [ ]:
# time taken by array
start_time = time.time()
newa = a * 2
time_taken_a = time.time() - start_time

print(f"Time taken by an array is {time_taken_a}")

Time taken by an array is 0.003496885299682617


In [ ]:
# how much faster
time_taken_l / time_taken_a

16.80227722097225